# Generated by Django 3.1.1 on 2020-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('borough', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('access', models.CharField(blank=True, default='', max_length=100)),
                ('disabled', models.BooleanField(blank=True, default=False)),
                ('wheelchair', models.BooleanField(blank=True, default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('male', models.BooleanField(blank=True, default=False)),
                ('female', models.BooleanField(blank=True, default=False)),
                ('unisex', models.BooleanField(blank=True, default=False)),
                ('changing_table', models.BooleanField(blank=True, default=False)),
                ('fee', models.TextField(blank=True, default='')),
                ('opening_hours', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
