# Generated by Django 3.1.1 on 2020-09-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='access',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='changing_table',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='female',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='male',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='note',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='unisex',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='wheelchair',
        ),
    ]
