# Generated by Django 3.1.1 on 2020-09-30 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='baby_change',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='toilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='toilets4london.toilet'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DNE', 'Toilet_does_not_exist'), ('NTP', 'No_toilet_paper'), ('LQ', 'Long_queue'), ('NH', 'Insufficient_hand_washing_facilities'), ('BOB', 'Toilet_blocked_or_broken'), ('NC', 'Facilities_not_clean'), ('O', 'Other')], max_length=3)),
                ('other_description', models.TextField(blank=True, default='')),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='toilets4london.toilet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'toilet')},
            },
        ),
    ]
