# Generated by Django 3.1.1 on 2020-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='toilet',
            name='opening_hours',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='toilet',
            name='wheelchair',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
