# Generated by Django 3.1.1 on 2020-09-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0004_auto_20200918_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='toilet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toilet', to='toilets4london.toilet'),
        ),
    ]
