# Generated by Django 3.1.1 on 2020-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0004_toilet_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='toilet',
            constraint=models.CheckConstraint(check=models.Q(longitude__isnull=False), name='Address or Coords provided'),
        ),
    ]
