# Generated by Django 3.1.1 on 2020-10-29 11:01

import Toilets4LondonAPI.toilets4london.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0006_auto_20201022_2130'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='toilet',
            name='Address or Coords provided',
        ),
        migrations.AlterField(
            model_name='report',
            name='other_description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('DNE', 'This toilet does not exist'), ('O', 'This toilet is very poorly maintained')], max_length=3),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='borough',
            field=models.CharField(choices=[('City of London', 'City of London'), ('Barking and Dagenham', 'Barking and Dagenham'), ('Barnet', 'Barnet'), ('Bexley', 'Bexley'), ('Brent', 'Brent'), ('Bromley', 'Bromley'), ('Camden', 'Camden'), ('Croydon', 'Croydon'), ('Ealing', 'Ealing'), ('Enfield', 'Enfield'), ('Greenwich', 'Greenwich'), ('Hackney', 'Hackney'), ('Hammersmith and Fulham', 'Hammersmith and Fulham'), ('Haringey', 'Haringey'), ('Harrow', 'Harrow'), ('Havering', 'Havering'), ('Hillingdon', 'Hillingdon'), ('Hounslow', 'Hounslow'), ('Islington', 'Islington'), ('Kensington and Chelsea', 'Kensington and Chelsea'), ('Kingston upon Thames', 'Kingston upon Thames'), ('Lambeth', 'Lambeth'), ('Lewisham', 'Lewisham'), ('Merton', 'Merton'), ('Newham', 'Newham'), ('Redbridge', 'Redbridge'), ('Richmond upon Thames', 'Richmond upon Thames'), ('Southwark', 'Southwark'), ('Sutton', 'Sutton'), ('Tower Hamlets', 'Tower Hamlets'), ('Waltham Forest', 'Waltham Forest'), ('Wandsworth', 'Wandsworth'), ('Westminster', 'Westminster')], max_length=100),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='latitude',
            field=models.FloatField(default=1, validators=[Toilets4LondonAPI.toilets4london.validators.validate_latitude]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toilet',
            name='longitude',
            field=models.FloatField(default=1, validators=[Toilets4LondonAPI.toilets4london.validators.validate_longitude]),
            preserve_default=False,
        ),
    ]
