# Generated by Django 3.1.1 on 2020-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0008_auto_20201029_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='borough',
            field=models.CharField(blank=True, default='Other', max_length=100),
        ),
    ]
