# Generated by Django 3.1.1 on 2020-11-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0011_auto_20201029_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='borough',
            field=models.CharField(choices=[('City of London', 'City of London'), ('Barking and Dagenham', 'Barking and Dagenham'), ('Barnet', 'Barnet'), ('Bexley', 'Bexley'), ('Brent', 'Brent'), ('Bromley', 'Bromley'), ('Camden', 'Camden'), ('Croydon', 'Croydon'), ('Ealing', 'Ealing'), ('Enfield', 'Enfield'), ('Greenwich', 'Greenwich'), ('Hackney', 'Hackney'), ('Hammersmith and Fulham', 'Hammersmith and Fulham'), ('Haringey', 'Haringey'), ('Harrow', 'Harrow'), ('Havering', 'Havering'), ('Hillingdon', 'Hillingdon'), ('Hounslow', 'Hounslow'), ('Islington', 'Islington'), ('Kensington and Chelsea', 'Kensington and Chelsea'), ('Kingston upon Thames', 'Kingston upon Thames'), ('Lambeth', 'Lambeth'), ('Lewisham', 'Lewisham'), ('Merton', 'Merton'), ('Newham', 'Newham'), ('Redbridge', 'Redbridge'), ('Richmond upon Thames', 'Richmond upon Thames'), ('Southwark', 'Southwark'), ('Sutton', 'Sutton'), ('Tower Hamlets', 'Tower Hamlets'), ('Waltham Forest', 'Waltham Forest'), ('Wandsworth', 'Wandsworth'), ('Westminster', 'Westminster'), ('', 'Other')], default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
