# Generated by Django 3.1.1 on 2020-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0012_auto_20201101_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='open',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
