# Generated by Django 3.1.1 on 2020-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0013_toilet_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='toilet',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('DNE', 'This toilet does not exist'), ('O', 'Other')], max_length=3),
        ),
    ]
