# Generated by Django 3.1.1 on 2021-02-23 23:41

import Toilets4LondonAPI.toilets4london.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilets4london', '0014_auto_20201115_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedToilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[Toilets4LondonAPI.toilets4london.validators.validate_latitude])),
                ('longitude', models.FloatField(validators=[Toilets4LondonAPI.toilets4london.validators.validate_longitude])),
                ('details', models.CharField(blank=True, default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
